# Generated by Django 5.0.6 on 2025-11-26 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('hak_akses', models.CharField(max_length=50)),
                ('email_admin', models.CharField(default='-', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pengirim', models.CharField(choices=[('pembeli', 'Pembeli'), ('penjual', 'Penjual')], max_length=10)),
                ('isi_pesan', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.CharField(max_length=100)),
                ('deskripsi_kategori', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id_keranjang', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeranjangItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('keranjang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.keranjang')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(max_length=100)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_pembayaran', models.CharField(default='Belum Dibayar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id_pembeli', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pengiriman', models.CharField(max_length=100)),
                ('alamat_pembeli', models.TextField()),
                ('no_resi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penjual',
            fields=[
                ('id_penjual', models.AutoField(primary_key=True, serialize=False)),
                ('nama_penjual', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat_toko', models.TextField()),
                ('status_toko', models.CharField(default='Aktif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=200)),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kategori')),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('alamat', models.TextField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status_transaksi', models.CharField(default='Pending', max_length=50)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli')),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga_saat_transaksi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id_ulasan', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produk')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='keranjang',
            name='pembeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli'),
        ),
        migrations.AddField(
            model_name='chat',
            name='pembeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli'),
        ),
        migrations.AddField(
            model_name='chat',
            name='penjual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual'),
        ),
        migrations.AddField(
            model_name='keranjangitem',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produk'),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='transaksi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.transaksi'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='transaksi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.transaksi'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
