# Generated by Django 5.0.6 on 2025-11-12 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nama_admin', models.CharField(max_length=100)),
                ('hak_akses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('isi_pesan', models.TextField()),
                ('waktu_pesan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ksategori', models.CharField(max_length=100)),
                ('deskripsi_kategori', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('status_pembayaran', models.CharField(default='Belum Dibayar', max_length=50)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id_pembeli', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id_pengiriman', models.AutoField(primary_key=True, serialize=False)),
                ('alamat_pembeli', models.TextField()),
                ('metode_pengiriman', models.CharField(max_length=100)),
                ('no_resi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penjual',
            fields=[
                ('id_penjual', models.AutoField(primary_key=True, serialize=False)),
                ('nama_penjual', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=15)),
                ('status_toko', models.CharField(default='Aktif', max_length=50)),
                ('mengelola_produk', models.TextField(blank=True, null=True)),
                ('alamat_toko', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=200)),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('id_kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kategori')),
                ('id_penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('alamat', models.TextField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_transaksi', models.CharField(default='Pending', max_length=50)),
                ('id_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembayaran')),
                ('id_pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli')),
                ('id_penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual')),
            ],
        ),
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id_ulasan', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('id_pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli')),
                ('id_penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='chat',
            name='id_pembeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pembeli'),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_penjual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.penjual'),
        ),
        migrations.AddField(
            model_name='pengiriman',
            name='id_transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transaksi'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='id_transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transaksi'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
