# Generated by Django 5.0.6 on 2025-11-12 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_chat_kategori_pembayaran_pembeli_pengiriman_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='nama_ksategori',
            new_name='nama_kategori',
        ),
        migrations.RenameField(
            model_name='pembeli',
            old_name='id_pembeli',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='pembeli',
            name='nama',
        ),
        migrations.AddField(
            model_name='pembeli',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
