# Generated by Django 5.0.6 on 2025-11-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nama_ksategori_kategori_nama_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembeli',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='id_pembayaran',
        ),
        migrations.AddField(
            model_name='pembeli',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='penjual',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penjual',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pembeli',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
